FROM node:lts-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:lts-alpine

RUN apk update && apk add --no-cache wget
RUN npm install -g http-server

WORKDIR /app
COPY --from=builder /app/dist ./dist

EXPOSE 5173
CMD [ "http-server", "dist", "-p", "5173" ]
