FROM node:lts-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run generate 

FROM node:lts-alpine

RUN apk update && apk add --no-cache wget
RUN npm install -g http-server

WORKDIR /app
COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD [ "http-server", "dist", "-p", "3000" ]
